// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "KineprintApp",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "KineprintApp",
            targets: ["AppModule"],
            bundleIdentifier: "com-adi-kineprintApp.KineprintApp",
            teamIdentifier: "PL2H83MN92",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.mint),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .camera(purposeString: "Kineprint uses the camera for offline augmented reality and motion tracking."),
                .microphone(purposeString: "Kineprint uses the microphone for offline spatial audio processing."),
                .motion(purposeString: "Kineprint uses sensors for offline motion tracking and spatial awareness."),
                .speechRecognition(purposeString: "Kineprint uses speech recognition for secure voice dictation operations.")
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            exclude: [
                "Package.swift",
                ".swiftpm"
            ]
        )
    ],
    swiftLanguageVersions: [.v5]
)