import Foundation

struct RevisionCard: Identifiable {
    let id = UUID()
    let category: String
    let code: String
    let title: String
    let formula: String
    let subtitle: String
    let deepElaboration: String
    let exampleText: String
    let examplePictogram: String
    let icon: String
}

let allRevisionCards: [RevisionCard] = [

    // ╔══════════════════════════════════════════════╗
    // ║          MATHEMATICS (14 Concepts)           ║
    // ╚══════════════════════════════════════════════╝

    RevisionCard(category: "MATHEMATICS", code: "MTH-001", title: "Euler's Identity", formula: "e^(iπ) + 1 = 0", subtitle: "The most beautiful equation linking 5 fundamental constants.", deepElaboration: "Connects e (growth), i (imaginary rotation), π (circles), 1 (multiplicative identity), and 0 (additive identity) into one formula. Arises from Euler's formula e^(ix) = cos(x) + i·sin(x). At x = π, cos(π) = −1 and sin(π) = 0, giving e^(iπ) = −1. Adding 1 yields zero. Used in complex analysis, quantum mechanics, and signal processing.", exampleText: "Walk halfway around a unit circle in the complex plane (π radians). You land exactly at −1 on the real axis. Add 1 and you're back at the origin — the universe balances perfectly.", examplePictogram: "circle.dashed", icon: "function"),

    RevisionCard(category: "MATHEMATICS", code: "MTH-002", title: "Navier-Stokes Equations", formula: "ρ(∂v/∂t + v·∇v) = −∇p + μ∇²v + f", subtitle: "Governs the motion of viscous fluids — a Millennium Prize Problem.", deepElaboration: "A set of nonlinear PDEs describing fluid velocity, pressure, and viscous forces. The left side is fluid inertia (acceleration); the right side includes pressure gradient, viscous diffusion, and external forces. Exact solutions for turbulence remain unsolved. Applied in aerodynamics, weather prediction, oceanography, and blood flow modeling.", exampleText: "An aircraft wing slicing through clouds — air flows smoothly over the top (laminar) but swirls into chaotic vortices at the trailing edge (turbulent) due to viscous friction and pressure gradients.", examplePictogram: "wind", icon: "wind"),

    RevisionCard(category: "MATHEMATICS", code: "MTH-003", title: "Eigenvalues & Eigenvectors", formula: "Ax = λx", subtitle: "Vectors unchanged in direction by a linear transformation.", deepElaboration: "When matrix A transforms eigenvector x, it only scales it by eigenvalue λ without rotating it. Finding eigenvalues: solve det(A − λI) = 0 (characteristic polynomial). Critical for PCA (dimensionality reduction), Google PageRank, vibration analysis, quantum mechanics (energy levels), and stability analysis of dynamic systems.", exampleText: "Stretch a rubber sheet along one axis. Arrows drawn exactly along the stretch direction only get longer — they're eigenvectors. All other arrows both rotate and stretch.", examplePictogram: "square.grid.3x3.topleft.filled", icon: "square.grid.3x3.topleft.filled"),

    RevisionCard(category: "MATHEMATICS", code: "MTH-004", title: "Fourier Transform", formula: "F(ω) = ∫ f(t)e^(−jωt) dt", subtitle: "Decomposes any signal into its constituent frequencies.", deepElaboration: "Converts a time-domain signal into the frequency domain. The inverse transform reconstructs the original signal from its spectrum. Discrete version (DFT/FFT) is O(n log n). Without Fourier analysis, MP3 compression, JPEG images, MRI scanning, noise cancellation, and spectroscopy would be impossible.", exampleText: "A piano chord sounds complex, but the Fourier Transform separates it into individual pure notes (C, E, G) — each with its own frequency, amplitude, and phase.", examplePictogram: "waveform", icon: "waveform"),

    RevisionCard(category: "MATHEMATICS", code: "MTH-005", title: "Taylor Series", formula: "f(x) = Σ f⁽ⁿ⁾(a)/n! · (x−a)ⁿ", subtitle: "Approximates any smooth function as an infinite polynomial.", deepElaboration: "By evaluating derivatives at a single point a, we predict function behavior everywhere nearby. Maclaurin series is Taylor at a=0. Examples: sin(x) = x − x³/3! + x⁵/5! − ..., e^x = 1 + x + x²/2! + ... Computers use truncated Taylor series to calculate transcendental functions. Convergence radius determines the valid approximation range.", exampleText: "Approximate a curve: first with a tangent line (n=1), then a parabola (n=2), then a cubic (n=3). Each added term bends the polynomial closer to the original curve until they're indistinguishable.", examplePictogram: "chart.xyaxis.line", icon: "chart.xyaxis.line"),

    RevisionCard(category: "MATHEMATICS", code: "MTH-006", title: "Laplace Transform", formula: "F(s) = ∫₀^∞ f(t)e^(−st) dt", subtitle: "Converts differential equations into algebraic equations.", deepElaboration: "Transforms functions of time t into functions of complex frequency s. Turns derivatives into multiplication by s: L{f'(t)} = sF(s) − f(0). Makes solving linear ODEs trivial — just algebra! Essential for control systems (transfer functions), circuit analysis (impedance), and signal processing. Inverse transform recovers the time-domain solution.", exampleText: "Instead of solving a messy differential equation directly, Laplace transforms it into simple algebra, you solve it easily, then transform back — like translating a hard book into an easy language, solving it, then translating back.", examplePictogram: "arrow.right.arrow.left", icon: "arrow.right.arrow.left"),

    RevisionCard(category: "MATHEMATICS", code: "MTH-007", title: "Bayes' Theorem", formula: "P(A|B) = P(B|A)·P(A) / P(B)", subtitle: "Updates probability based on new evidence.", deepElaboration: "The foundation of probabilistic inference. Prior probability P(A) is updated to posterior P(A|B) when evidence B is observed. Used everywhere: spam filters, medical diagnosis, machine learning (Naive Bayes classifier), A/B testing, forensic DNA matching. Bayesian inference is the mathematical framework for learning from data.", exampleText: "A medical test is 99% accurate. You test positive. But if only 1 in 10,000 people have the disease, Bayes' theorem shows there's still only a ~1% chance you actually have it — because false positives overwhelm true positives.", examplePictogram: "chart.pie.fill", icon: "chart.pie.fill"),

    RevisionCard(category: "MATHEMATICS", code: "MTH-008", title: "Green's Theorem", formula: "∮ F·dr = ∬ (∂Q/∂x − ∂P/∂y) dA", subtitle: "Relates a line integral around a curve to a double integral over the region.", deepElaboration: "Connects circulation around a closed curve C to the curl of the vector field inside the region D. Special case of Stokes' theorem in 2D. Used to convert difficult line integrals into easier area integrals. Applications: computing work done by a force field, fluid circulation, electromagnetism, and area computation via line integrals.", exampleText: "Instead of walking the entire perimeter of a lake measuring water flow at every point, Green's theorem lets you calculate total circulation by analyzing the spinning motion (curl) everywhere inside the lake.", examplePictogram: "circle.grid.cross.fill", icon: "circle.grid.cross.fill"),

    RevisionCard(category: "MATHEMATICS", code: "MTH-009", title: "Stokes' Theorem", formula: "∮ F·dr = ∬ (∇×F)·dS", subtitle: "The 3D generalization of Green's theorem.", deepElaboration: "Relates the circulation of a vector field around a closed curve to the surface integral of its curl over any surface bounded by that curve. Unifies Green's theorem, divergence theorem, and fundamental theorem of calculus. Critical in electromagnetism (Faraday's law), fluid dynamics, and differential geometry.", exampleText: "A tornado forms when air circulation around a boundary intensifies. Stokes' theorem says the total swirl along the edge equals the sum of all the tiny rotational vortices across the entire enclosed surface.", examplePictogram: "tornado", icon: "tornado"),

    RevisionCard(category: "MATHEMATICS", code: "MTH-010", title: "Matrix Determinants", formula: "det(A) = Σ (−1)^σ · ∏ a_{i,σ(i)}", subtitle: "A scalar encoding key properties of a linear transformation.", deepElaboration: "The determinant tells you: (1) if a matrix is invertible (det ≠ 0), (2) the scaling factor of areas/volumes under the transformation, (3) orientation preservation (det > 0) or reversal (det < 0). For 2×2: det = ad − bc. Cramer's rule uses determinants to solve linear systems. Eigenvalues satisfy det(A − λI) = 0.", exampleText: "A 2×2 matrix transforms a unit square. The determinant tells you the area of the resulting parallelogram. If det = 2, the area doubled. If det = −1, the area is preserved but the shape got flipped (mirror image).", examplePictogram: "square.grid.3x3", icon: "square.grid.3x3"),

    RevisionCard(category: "MATHEMATICS", code: "MTH-011", title: "Divergence Theorem", formula: "∯ F·dS = ∭ (∇·F) dV", subtitle: "Total flux through a surface equals divergence summed over volume.", deepElaboration: "Also called Gauss's theorem. Converts a surface integral into a volume integral. If ∇·F > 0, the field is a source (expanding). If ∇·F < 0, it's a sink (contracting). Fundamental to electromagnetism (Gauss's law: ∯ E·dS = Q/ε₀), fluid dynamics (mass conservation), and heat transfer.", exampleText: "Imagine an inflating balloon — air flows outward through every point of the surface. The divergence theorem says the total airflow out equals the sum of all the expansion happening inside the balloon.", examplePictogram: "arrow.up.left.and.arrow.down.right", icon: "arrow.up.left.and.arrow.down.right"),

    RevisionCard(category: "MATHEMATICS", code: "MTH-012", title: "Cauchy's Integral Theorem", formula: "∮ f(z) dz = 0", subtitle: "A holomorphic function integrated around a closed loop gives zero.", deepElaboration: "If f(z) is analytic (complex differentiable) everywhere inside a closed contour C, then the integral around C vanishes. The powerful corollary — Cauchy's integral formula — lets you compute f(a) at any interior point from boundary values alone. Foundation of residue calculus, used to evaluate real integrals that seem impossible otherwise.", exampleText: "Walk around the edge of a smooth hill logging the height at every step. If the hill is perfectly smooth everywhere inside your path, the total height change after one full loop is exactly zero.", examplePictogram: "point.topleft.down.curvedto.point.bottomright.up", icon: "point.topleft.down.curvedto.point.bottomright.up"),

    RevisionCard(category: "MATHEMATICS", code: "MTH-013", title: "Riemann Hypothesis", formula: "ζ(s) = 0 ⟹ Re(s) = ½", subtitle: "The deepest unsolved problem about prime number distribution.", deepElaboration: "Conjectures that all non-trivial zeros of the Riemann zeta function ζ(s) = Σ 1/n^s lie on the critical line Re(s) = ½ in the complex plane. If proven, it would reveal the exact pattern of prime numbers, revolutionizing cryptography, number theory, and quantum physics. A $1 million Millennium Prize Problem.", exampleText: "Prime numbers seem randomly scattered, but they follow a hidden rhythm. The Riemann zeros are like GPS coordinates of this rhythm — and they all mysteriously line up along one single vertical line.", examplePictogram: "grid", icon: "grid"),

    RevisionCard(category: "MATHEMATICS", code: "MTH-014", title: "Linear Differential Equations", formula: "aₙy⁽ⁿ⁾ + ... + a₁y' + a₀y = f(x)", subtitle: "Equations relating a function to its derivatives — the language of physics.", deepElaboration: "Classified by order (highest derivative), linearity, and homogeneity. Solution methods: separation of variables, integrating factors, characteristic equations (for constant coefficients), variation of parameters, and power series. Every physical law (Newton, Maxwell, Schrödinger) is an ODE or PDE at its core.", exampleText: "A spring-mass system: mx'' + cx' + kx = 0. The solution tells you exactly how the mass oscillates over time — underdamped (bouncing), critically damped (fastest stop), or overdamped (sluggish return).", examplePictogram: "waveform.path", icon: "waveform.path"),

    // ╔══════════════════════════════════════════════╗
    // ║        QUANTUM PHYSICS (10 Concepts)         ║
    // ╚══════════════════════════════════════════════╝

    RevisionCard(category: "QUANTUM PHYSICS", code: "QTM-001", title: "Schrödinger Equation", formula: "iℏ ∂Ψ/∂t = HΨ", subtitle: "Governs the wave function of a quantum system.", deepElaboration: "The time-dependent Schrödinger equation describes how quantum states evolve. Ψ is the wave function — |Ψ|² gives the probability density. H is the Hamiltonian operator (total energy). The time-independent version HΨ = EΨ gives energy eigenvalues. Solving it yields atomic orbitals, molecular bonds, and semiconductor behavior.", exampleText: "An electron doesn't orbit like a planet. It exists as a probability cloud — denser regions mean higher chance of finding it there. The Schrödinger equation computes this cloud's exact shape.", examplePictogram: "atom", icon: "atom"),

    RevisionCard(category: "QUANTUM PHYSICS", code: "QTM-002", title: "Heisenberg Uncertainty", formula: "ΔxΔp ≥ ℏ/2", subtitle: "Fundamental limit to simultaneously measuring position and momentum.", deepElaboration: "Not a measurement limitation — it's a property of nature itself. A particle's position and momentum are conjugate variables related by Fourier transform. Localizing one necessarily spreads the other. Also applies to energy-time: ΔEΔt ≥ ℏ/2 (explains virtual particles). Defines the quantum limit of all sensors and instruments.", exampleText: "Photograph a speeding bullet: sharp photo = you know its position but not speed (blur). Fast shutter = sharper but dimmer. You physically cannot get both perfect — that's Heisenberg.", examplePictogram: "aqi.medium", icon: "aqi.medium"),

    RevisionCard(category: "QUANTUM PHYSICS", code: "QTM-003", title: "Quantum Entanglement", formula: "|Ψ⟩ = (|00⟩ + |11⟩)/√2", subtitle: "Instant correlation between particles regardless of distance.", deepElaboration: "When two particles are entangled, measuring one instantly determines the other's state — even across galaxies. Not communication (no information transfer), but correlation stronger than any classical system. Bell's theorem (1964) proved this isn't hidden variables. Basis for quantum cryptography (QKD), quantum teleportation, and quantum computing.", exampleText: "Two entangled coins: flip one and get Heads → the other is guaranteed Tails instantly, even on Mars. Zero delay. Einstein called it 'spooky action at a distance' — but Bell proved it's real.", examplePictogram: "link", icon: "link"),

    RevisionCard(category: "QUANTUM PHYSICS", code: "QTM-004", title: "Wave-Function Collapse", formula: "Ψ → φᵢ with P = |⟨φᵢ|Ψ⟩|²", subtitle: "Observation forces superposition into a single definite state.", deepElaboration: "Before measurement, a quantum system exists in a superposition of all possible states. The act of observation projects Ψ onto an eigenstate φᵢ with probability given by the Born rule |⟨φᵢ|Ψ⟩|². After collapse, repeated measurements give the same result. The measurement problem — why collapse happens — remains debated (Copenhagen, Many-Worlds, decoherence).", exampleText: "Schrödinger's cat: both alive AND dead simultaneously in superposition until you open the box. The universe 'chooses' an outcome only when you look — that's wave-function collapse.", examplePictogram: "eye", icon: "eye"),

    RevisionCard(category: "QUANTUM PHYSICS", code: "QTM-005", title: "Quantum Tunneling", formula: "T ≈ e^(−2κa)", subtitle: "Particles penetrating classically forbidden energy barriers.", deepElaboration: "Because particles are probability waves, their wave function decays exponentially inside a barrier but doesn't reach zero — so there's a non-zero probability of appearing on the other side. Tunneling probability T depends on barrier width a and height via κ = √(2m(V-E))/ℏ. Enables: nuclear fusion in stars, tunnel diodes, scanning tunneling microscopes, and flash memory.", exampleText: "A ball thrown at a wall should bounce back. But at quantum scale, there's a tiny chance it just materializes on the other side. This is how the Sun fuses hydrogen — protons tunnel through their repulsive barrier.", examplePictogram: "arrow.right.to.line.alt", icon: "arrow.right.to.line.alt"),

    RevisionCard(category: "QUANTUM PHYSICS", code: "QTM-006", title: "Pauli Exclusion Principle", formula: "Ψ(x₁,x₂) = −Ψ(x₂,x₁)", subtitle: "No two identical fermions can share the same quantum state.", deepElaboration: "Fermions (electrons, protons, neutrons) have antisymmetric wave functions. Swapping two identical fermions flips the sign, so if they're in the same state, Ψ = −Ψ → Ψ = 0 (impossible). This forces electrons into different orbitals, creating the periodic table, chemistry, solid matter, and white dwarf/neutron star stability.", exampleText: "Two identical bar magnets forced to stack perfectly aligned — they violently repel. This quantum repulsion is why your hand doesn't phase through the table. Electron shells exist because electrons refuse to share states.", examplePictogram: "magnet", icon: "magnet"),

    RevisionCard(category: "QUANTUM PHYSICS", code: "QTM-007", title: "Planck's Radiation Law", formula: "E = hf = hc/λ", subtitle: "Energy is quantized — it comes in discrete packets.", deepElaboration: "Max Planck (1900) resolved the ultraviolet catastrophe by proposing energy is emitted in quanta E = hf, where h = 6.626×10⁻³⁴ J·s. This birthed quantum mechanics. Planck's blackbody spectrum: B(λ,T) = (2hc²/λ⁵)/(e^(hc/λkT) − 1). Explains why hot objects glow red then white, the cosmic microwave background, and LED color selection.", exampleText: "A glowing iron bar: classical physics predicted infinite energy at short wavelengths (ultraviolet catastrophe). Planck fixed it by saying energy comes in chunks — hotter objects emit bluer chunks, which is why white-hot is hotter than red-hot.", examplePictogram: "light.max", icon: "light.max"),

    RevisionCard(category: "QUANTUM PHYSICS", code: "QTM-008", title: "De Broglie Wavelength", formula: "λ = h/p = h/(mv)", subtitle: "Every particle has an associated wave — matter is a wave too.", deepElaboration: "Louis de Broglie (1924) proposed that particles exhibit wave behavior with wavelength inversely proportional to momentum. Confirmed by electron diffraction experiments (Davisson-Germer, 1927). For macroscopic objects, λ is astronomically small (undetectable). For electrons, λ ≈ atomic spacing → enables electron microscopy, neutron diffraction, and quantum computing.", exampleText: "A thrown baseball has a wavelength — but it's 10⁻³⁴ meters (way smaller than a proton). An electron moving slowly, however, has wavelength comparable to atomic spacing, so it diffracts through crystal lattices like light through a slit.", examplePictogram: "wave.3.right", icon: "wave.3.right"),

    RevisionCard(category: "QUANTUM PHYSICS", code: "QTM-009", title: "Compton Scattering", formula: "Δλ = (h/mₑc)(1 − cosθ)", subtitle: "X-ray photons lose energy when bouncing off electrons.", deepElaboration: "Arthur Compton (1923) proved photons have momentum by showing X-rays increase in wavelength after scattering off electrons. The wavelength shift depends only on scattering angle θ, not the incident wavelength. Proved the particle nature of light conclusively. h/mₑc = 2.43 pm is the Compton wavelength of the electron.", exampleText: "Shoot a billiard ball (photon) at a stationary ball (electron). After collision, the cue ball bounces away slower (longer wavelength) and the target ball recoils. Same physics, just at quantum scale with X-rays.", examplePictogram: "arrow.triangle.branch", icon: "arrow.triangle.branch"),

    RevisionCard(category: "QUANTUM PHYSICS", code: "QTM-010", title: "Dirac Equation", formula: "(iγᵘ∂ᵤ − m)ψ = 0", subtitle: "Relativistic wave equation predicting antimatter.", deepElaboration: "Paul Dirac (1928) merged special relativity with quantum mechanics. Unlike Schrödinger's equation, it's first-order in both space and time derivatives. Its solutions naturally include negative-energy states — predicted antimatter (positrons, discovered 1932). Also explains electron spin as a relativistic effect, not an add-on. Foundation of quantum field theory and the Standard Model.", exampleText: "Dirac's equation had 'impossible' negative-energy solutions. Instead of discarding them, he predicted they meant anti-electrons (positrons) must exist. Anderson found positrons in cosmic rays 4 years later — pure mathematical prediction confirmed by nature.", examplePictogram: "sparkles", icon: "sparkles"),

    // ╔══════════════════════════════════════════════╗
    // ║           AI & IOT (10 Concepts)             ║
    // ╚══════════════════════════════════════════════╝

    RevisionCard(category: "AI & IOT", code: "AIO-001", title: "Backpropagation", formula: "Δw = −η(∂E/∂w)", subtitle: "The core training algorithm for neural networks.", deepElaboration: "Uses the chain rule to compute the gradient of the loss function with respect to every weight. Forward pass computes output; backward pass propagates error gradients from output layer back to input layer. Weights updated via gradient descent: w = w − η·∂E/∂w. Variants: SGD, Adam, RMSprop. Makes deep learning possible — without backprop, neural networks cannot learn.", exampleText: "A blindfolded hiker descends a mountain by feeling the slope under their feet. Each step follows the steepest downhill direction. Backprop computes that 'slope' for millions of parameters simultaneously.", examplePictogram: "network", icon: "network"),

    RevisionCard(category: "AI & IOT", code: "AIO-002", title: "Shannon's Channel Capacity", formula: "C = B log₂(1 + S/N)", subtitle: "Maximum error-free data rate over a noisy channel.", deepElaboration: "Claude Shannon (1948) proved every channel has a theoretical maximum throughput C (bits/second) determined by bandwidth B (Hz) and signal-to-noise ratio S/N. You can approach C with error-correcting codes but never exceed it. Governs WiFi speeds, 5G design, satellite links, and all IoT communication. Higher SNR or bandwidth → more capacity.", exampleText: "Trying to talk next to a jet engine (noise). Either yell louder (increase signal), talk slower (reduce data rate), or use a bigger megaphone (more bandwidth). Shannon's law defines the absolute maximum you can ever achieve.", examplePictogram: "antenna.radiowaves.left.and.right", icon: "antenna.radiowaves.left.and.right"),

    RevisionCard(category: "AI & IOT", code: "AIO-003", title: "MQTT Protocol", formula: "Publish → Broker → Subscribe", subtitle: "Lightweight messaging for IoT — minimal bandwidth, maximum reliability.", deepElaboration: "Message Queuing Telemetry Transport uses a publish-subscribe model via a central broker. Topics organize messages hierarchically (e.g., home/kitchen/temperature). QoS levels: 0 (fire-and-forget), 1 (at-least-once), 2 (exactly-once). Uses minimal overhead — a CONNECT packet is just 2 bytes. Perfect for battery-powered sensors, smart homes, industrial IoT, and fleet tracking.", exampleText: "Instead of calling the weather station every 5 seconds (client-server), you subscribe to 'Weather updates'. When it rains, the broker pushes you a notification instantly — no polling, no wasted bandwidth.", examplePictogram: "server.rack", icon: "server.rack"),

    RevisionCard(category: "AI & IOT", code: "AIO-004", title: "Gradient Descent", formula: "θ = θ − α∇J(θ)", subtitle: "Iterative optimizer finding the minimum of a cost function.", deepElaboration: "Compute gradient ∇J (direction of steepest ascent), then step in the opposite direction by learning rate α. Variants: Batch (full dataset), Stochastic (one sample), Mini-batch (subset). Advanced optimizers: Adam (adaptive learning rates), RMSprop (momentum), AdaGrad (per-parameter rates). Convergence depends on learning rate — too high diverges, too low stalls.", exampleText: "A ball rolling down a bumpy hill. It follows the steepest slope at each point. If it rolls too fast (high α), it overshoots the valley. Too slow, it takes forever. Gradient descent finds the perfect pace.", examplePictogram: "chart.line.uptrend.xyaxis", icon: "chart.line.uptrend.xyaxis"),

    RevisionCard(category: "AI & IOT", code: "AIO-005", title: "Convolutional Neural Networks", formula: "G[i,j] = ΣΣ K[u,v]·I[i−u,j−v]", subtitle: "The visual cortex of AI — detects features in images.", deepElaboration: "Applies learnable filter kernels (3×3, 5×5) that slide across the image computing dot products. Early layers detect edges; deeper layers detect shapes, textures, then objects. Architecture: Conv → ReLU → Pool → Conv → ... → Flatten → Dense. Parameters shared across spatial locations (translation invariance). Powers: face detection, self-driving cars, medical imaging, satellite analysis.", exampleText: "A magnifying glass that only detects vertical edges. Slide it across a car photo — only door seams and wheel spokes light up. CNN stacks hundreds of such specialized detectors to recognize the entire car.", examplePictogram: "viewfinder", icon: "viewfinder"),

    RevisionCard(category: "AI & IOT", code: "AIO-006", title: "Edge Computing", formula: "Latency → 0, Privacy → Max", subtitle: "Processing data locally where it's generated — no cloud needed.", deepElaboration: "Instead of sending raw data to distant cloud servers (adding latency, bandwidth cost, privacy risk), edge computing processes data on the device itself or nearby edge servers. Critical for: autonomous vehicles (can't wait 100ms for cloud response), AR/VR (real-time rendering), industrial IoT (factory floor decisions), and healthcare (patient data stays local).", exampleText: "A Tesla detecting a pedestrian. If it uploaded the camera frame to AWS Virginia, waited for processing, and received 'BRAKE' — the car would have already crashed. Edge AI processes on the bumper chip in 5ms.", examplePictogram: "cpu", icon: "cpu"),

    RevisionCard(category: "AI & IOT", code: "AIO-007", title: "Attention Mechanism", formula: "Attn(Q,K,V) = softmax(QKᵀ/√d)V", subtitle: "The transformer's core — lets AI focus on what matters.", deepElaboration: "Query Q asks 'what am I looking for?', Key K says 'what do I contain?', Value V says 'here's my content'. QKᵀ computes relevance scores, softmax normalizes to probabilities, then weighted sum of V gives context-aware output. Multi-head attention runs several in parallel. Powers: GPT, BERT, ChatGPT, DALL-E, protein folding (AlphaFold).", exampleText: "Reading 'The cat sat on the mat because it was tired' — when processing 'it', attention looks back and assigns high weight to 'cat' (not 'mat'), understanding the pronoun refers to the cat. That's self-attention.", examplePictogram: "text.magnifyingglass", icon: "text.magnifyingglass"),

    RevisionCard(category: "AI & IOT", code: "AIO-008", title: "Reinforcement Learning", formula: "Q(s,a) = r + γ·max Q(s',a')", subtitle: "AI learns optimal behavior through trial, error, and reward.", deepElaboration: "An agent interacts with an environment, receives rewards/penalties, and learns a policy mapping states to actions. Q-learning estimates value of actions without a model. Deep Q-Networks (DQN) use neural networks for complex state spaces. Policy gradient methods (PPO, A3C) optimize the policy directly. Trained AlphaGo, robotic manipulation, game AI, and autonomous driving.", exampleText: "A robot learning to walk: initially it flails randomly and falls (penalty). Eventually, certain leg movements keep it upright (reward). After millions of tries, it discovers smooth walking — no programmer told it how, it learned from experience.", examplePictogram: "gamecontroller.fill", icon: "gamecontroller.fill"),

    RevisionCard(category: "AI & IOT", code: "AIO-009", title: "GANs", formula: "min_G max_D [log D(x) + log(1−D(G(z)))]", subtitle: "Two neural networks competing to generate realistic data.", deepElaboration: "Generator G creates fake data from noise z; Discriminator D tries to distinguish real from fake. They play a minimax game — G improves at fooling D, D improves at detecting fakes. At equilibrium, G produces indistinguishable outputs. Applications: deepfakes, art generation, super-resolution, drug discovery, data augmentation, and style transfer.", exampleText: "An art forger (Generator) creates fake Picassos. An art critic (Discriminator) tries to spot fakes. They train against each other until the forger's work is indistinguishable from real Picassos.", examplePictogram: "paintbrush.fill", icon: "paintbrush.fill"),

    RevisionCard(category: "AI & IOT", code: "AIO-010", title: "Transfer Learning", formula: "θ_target = fine-tune(θ_source)", subtitle: "Reuse knowledge from one task to accelerate learning on another.", deepElaboration: "Pre-train a large model on massive data (ImageNet, Wikipedia), then fine-tune the last few layers on your specific small dataset. The early layers (edges, textures, grammar) transfer universally. Reduces training time from weeks to hours and data requirements from millions to thousands. Powers: BERT fine-tuning for sentiment analysis, medical imaging from ImageNet, and few-shot learning.", exampleText: "Learning to play tennis is faster if you already know badminton — the wrist movements, footwork, and court sense transfer. Transfer learning lets AI reuse 'athletic instincts' trained on one sport for another.", examplePictogram: "arrow.triangle.2.circlepath.doc.on.clipboard", icon: "arrow.triangle.2.circlepath.doc.on.clipboard"),

    // ╔══════════════════════════════════════════════╗
    // ║    MECHANICS & ENGINEERING (15 Concepts)     ║
    // ╚══════════════════════════════════════════════╝

    RevisionCard(category: "MECHANICS & ENGINEERING", code: "MEC-001", title: "Newton's Second Law", formula: "ΣF = ma = m(d²x/dt²)", subtitle: "The fundamental equation of classical mechanics.", deepElaboration: "Force equals mass times acceleration. This second-order ODE is the starting point for analyzing ALL mechanical systems — from pendulums to rocket trajectories. More general form: F = dp/dt (rate of change of momentum). When ΣF = 0, the object is in equilibrium (Newton's First Law). Paired with Newton's Third Law (action-reaction), it forms the complete Newtonian framework.", exampleText: "Push a bowling ball and a boulder with the same force. The bowling ball accelerates dramatically while the boulder barely budges — same force, different mass, different acceleration. F = ma in action.", examplePictogram: "arrow.up.and.down.and.arrow.left.and.right", icon: "arrow.up.and.down.and.arrow.left.and.right"),

    RevisionCard(category: "MECHANICS & ENGINEERING", code: "MEC-002", title: "Conservation of Momentum", formula: "Σp_initial = Σp_final", subtitle: "Total momentum is constant in an isolated system.", deepElaboration: "Momentum p = mv is conserved when no external forces act. In elastic collisions, both momentum and kinetic energy are conserved. In inelastic collisions, momentum is conserved but KE is not (some converts to heat/sound). Applies to: billiard balls, car crashes (accident reconstruction), rocket propulsion (thrust = Δp/Δt), and particle physics (conservation in decays).", exampleText: "Fire a rifle on ice skates. The tiny bullet flies forward fast; your massive body slides backward slowly — but both momenta are exactly equal and opposite. Total momentum: still zero.", examplePictogram: "car.2.fill", icon: "car.2.fill"),

    RevisionCard(category: "MECHANICS & ENGINEERING", code: "MEC-003", title: "Work-Energy Theorem", formula: "W_net = ΔK = ½mv²_f − ½mv²_i", subtitle: "Net work done equals the change in kinetic energy.", deepElaboration: "A powerful shortcut: instead of tracking forces and accelerations through complex paths, just compare initial and final kinetic energy states. W = F·d·cosθ for constant force; W = ∫F·dx for variable force. Conservation of energy: K + U = constant (for conservative forces). Explains braking distances (quadruple with doubled speed), roller coasters, and impact forces.", exampleText: "A truck doubles its speed from 30 to 60 mph. Braking distance quadruples — not doubles — because kinetic energy scales with v². That's why speeding tickets exist; physics makes fast crashes exponentially deadlier.", examplePictogram: "bolt.fill", icon: "bolt.fill"),

    RevisionCard(category: "MECHANICS & ENGINEERING", code: "MEC-004", title: "Rotational Inertia", formula: "I = Σ(mr²) | τ = Iα", subtitle: "Resistance to changes in rotational motion.", deepElaboration: "Moment of inertia I is the rotational analog of mass. Depends on both mass AND its distribution relative to the axis. A hollow cylinder has higher I than a solid one (same mass, radius). Parallel axis theorem: I = I_cm + Md². Torque τ = Iα is the rotational Newton's second law. Applications: flywheels, gyroscopes, figure skating spins, spacecraft attitude control.", exampleText: "An ice skater spinning: arms extended (large r) → slow spin. Arms pulled in (small r) → I decreases → angular velocity skyrockets to conserve angular momentum. Same principle stabilizes satellites.", examplePictogram: "arrow.triangle.2.circlepath", icon: "arrow.triangle.2.circlepath"),

    RevisionCard(category: "MECHANICS & ENGINEERING", code: "MEC-005", title: "Centripetal Acceleration", formula: "a_c = v²/r = ω²r", subtitle: "Acceleration directed toward the center of circular motion.", deepElaboration: "Moving in a circle requires continuous acceleration (velocity direction changes even at constant speed). The centripetal force F_c = mv²/r is always center-seeking — it's NOT a new force but provided by tension, gravity, friction, or normal force. Applications: satellite orbits, banked roads, centrifuges, artificial gravity in rotating space stations.", exampleText: "Swinging a bucket of water over your head — the rope provides centripetal force pointing inward. The water stays in the bucket because the circular acceleration acts like artificial gravity pinning it to the bottom.", examplePictogram: "circle.circle", icon: "circle.circle"),

    RevisionCard(category: "MECHANICS & ENGINEERING", code: "MEC-006", title: "Escape Velocity", formula: "v_e = √(2GM/r)", subtitle: "Minimum speed to escape a gravitational field.", deepElaboration: "Derived from conservation of energy: ½mv² = GMm/r. At escape velocity, a projectile reaches infinity with zero residual speed. For Earth: v_e ≈ 11.2 km/s. For the Moon: 2.4 km/s. For a black hole: v_e > c (light can't escape). Independent of the projectile's mass! Determines rocket fuel requirements, gravitational slingshots, and black hole event horizons.", exampleText: "Fire a cannonball at 8 km/s from a mountaintop — it orbits Earth. At 11.2 km/s — it escapes Earth forever. At just below 11.2 km/s, it falls back. That razor-thin speed boundary is escape velocity.", examplePictogram: "globe", icon: "globe"),

    RevisionCard(category: "MECHANICS & ENGINEERING", code: "MEC-007", title: "Critical Damping", formula: "c_crit = 2√(mk)", subtitle: "Fastest return to equilibrium without oscillation.", deepElaboration: "Damped harmonic oscillator: mx'' + cx' + kx = 0. Three regimes: underdamped (c < c_crit, oscillates), critically damped (c = c_crit, fastest non-oscillatory return), overdamped (c > c_crit, slow sluggish return). Discriminant Δ = c² − 4mk determines regime. Critical damping is optimal for: car suspensions, door closers, galvanometer needles, and servo control systems.", exampleText: "A car hits a pothole: underdamped suspension bounces repeatedly (uncomfortable), overdamped returns too slowly (unsafe), critically damped absorbs the shock and returns to level in minimum time — one smooth motion.", examplePictogram: "figure.walk", icon: "figure.walk"),

    RevisionCard(category: "MECHANICS & ENGINEERING", code: "MEC-008", title: "Maxwell's Equations", formula: "∇·E = ρ/ε₀ | ∇×B = μ₀J + μ₀ε₀∂E/∂t", subtitle: "The four equations governing all electromagnetic phenomena.", deepElaboration: "1) Gauss's law (E): charges create electric fields. 2) Gauss's law (B): no magnetic monopoles. 3) Faraday's law: changing B creates E (generators). 4) Ampère-Maxwell: current and changing E create B (electromagnets). Together they predict electromagnetic waves traveling at c = 1/√(μ₀ε₀) — proving light is an EM wave. Foundation of all electrical engineering.", exampleText: "Wave a magnet near a coil — changing magnetic field creates electric current (Faraday). That current creates its own magnetic field (Ampère). This feedback loop IS an electromagnetic wave — it's light itself!", examplePictogram: "bolt.horizontal.circle", icon: "bolt.horizontal.circle"),

    RevisionCard(category: "MECHANICS & ENGINEERING", code: "MEC-009", title: "Bernoulli's Principle", formula: "P + ½ρv² + ρgh = constant", subtitle: "Faster fluid flow creates lower pressure.", deepElaboration: "Conservation of energy applied to fluid flow along a streamline. When velocity increases (pipe narrows), pressure decreases, and vice versa. Assumes: incompressible, inviscid, steady, irrotational flow. Explains: airplane lift (faster air over curved wing = lower pressure on top), Venturi effect (carburetors), atomizers, and why shower curtains blow inward.", exampleText: "Blow horizontally over a curved piece of paper — it lifts! The fast-moving air above has lower pressure than the still air below. This pressure difference is what makes 400-ton airplanes fly.", examplePictogram: "airplane", icon: "airplane"),

    RevisionCard(category: "MECHANICS & ENGINEERING", code: "MEC-010", title: "Hooke's Law", formula: "F = −kx | σ = Eε", subtitle: "Spring force is proportional to displacement.", deepElaboration: "F = −kx: restorative force is proportional to extension x (valid in elastic region). k is the spring constant (N/m). Stress-strain relation: σ = Eε where E is Young's modulus (material stiffness). Beyond elastic limit: plastic deformation (permanent). Beyond ultimate strength: fracture. Applications: spring design, structural engineering, seismology, AFM probes.", exampleText: "Stretch a rubber band: it pulls back proportionally to how far you stretch. But stretch too far and it deforms permanently (plastic region). Further still — it snaps (fracture). Hooke's law governs the safe zone.", examplePictogram: "building.2", icon: "building.2"),

    RevisionCard(category: "MECHANICS & ENGINEERING", code: "MEC-011", title: "Bragg's Law", formula: "nλ = 2d sinθ", subtitle: "X-ray diffraction reveals crystal atomic structure.", deepElaboration: "When X-rays hit a crystal, they scatter off parallel atomic planes. Constructive interference occurs when the path difference equals whole wavelengths: 2d sinθ = nλ. By measuring diffraction angles θ, we determine interplanar spacing d and reconstruct 3D atomic structures. Used for: DNA double helix discovery (Rosalind Franklin), mineral identification, drug design, and semiconductor characterization.", exampleText: "Shine a laser through a fine comb — the light creates a dot pattern on the wall. Measuring dot spacing reveals the exact gap between comb teeth. Bragg's law does the same with X-rays and atoms.", examplePictogram: "diamond", icon: "diamond"),

    RevisionCard(category: "MECHANICS & ENGINEERING", code: "MEC-012", title: "Semiconductor Band Gap", formula: "Eg = Ec − Ev", subtitle: "Energy gap determining conductor/insulator/semiconductor behavior.", deepElaboration: "Electrons in solids occupy energy bands separated by forbidden gaps. Conductors: bands overlap (no gap). Insulators: Eg > 4 eV (too wide to jump). Semiconductors: Eg ≈ 0.5-3 eV (jumpable with heat/light/voltage). Silicon: 1.12 eV. Doping adds donors (n-type) or acceptors (p-type). P-N junctions create diodes, transistors, LEDs, solar cells — the foundation of ALL modern electronics.", exampleText: "Basketball through a hoop: insulator hoop is 100 feet high (impossible jump). Conductor hoop is on the ground (free walk-through). Semiconductor hoop is exactly 10 feet — a precise energy boost (voltage) lets the electron-ball score.", examplePictogram: "memorychip", icon: "memorychip"),

    RevisionCard(category: "MECHANICS & ENGINEERING", code: "MEC-013", title: "Ohm's Law & Kirchhoff's Laws", formula: "V = IR | ΣV = 0 | ΣI = 0", subtitle: "The fundamental rules for analyzing electrical circuits.", deepElaboration: "Ohm's Law: voltage across a resistor equals current times resistance. KVL (Kirchhoff's Voltage Law): sum of voltages around any closed loop is zero (energy conservation). KCL (Kirchhoff's Current Law): sum of currents entering a node equals sum leaving (charge conservation). Together they solve any linear circuit — series, parallel, bridge, mesh, and nodal analysis.", exampleText: "A water pipe system: V = water pressure, I = flow rate, R = pipe narrowness. Kirchhoff's laws say: total pressure drops around a loop sum to zero, and water entering a junction must equal water leaving. Exact same math as circuits.", examplePictogram: "bolt.circle", icon: "bolt.circle"),

    RevisionCard(category: "MECHANICS & ENGINEERING", code: "MEC-014", title: "Carnot Cycle", formula: "η = 1 − T_cold/T_hot", subtitle: "Maximum theoretical efficiency of any heat engine.", deepElaboration: "Sadi Carnot (1824) proved no engine can be more efficient than one running the Carnot cycle: isothermal expansion, adiabatic expansion, isothermal compression, adiabatic compression. Efficiency depends ONLY on temperature ratio. At T_cold = 0K, η = 100% (Third Law forbids this). Real engines (Otto, Diesel, Rankine) never reach Carnot efficiency due to friction, irreversibilities, and heat losses.", exampleText: "A car engine: hot gas (explosion, T_hot ≈ 2000K) pushes a piston (work output), then exhaust heat dumps to atmosphere (T_cold ≈ 300K). Carnot says max efficiency = 1 − 300/2000 = 85%. Real engines achieve ~25-40% — the rest is waste heat.", examplePictogram: "thermometer.medium", icon: "thermometer.medium"),

    RevisionCard(category: "MECHANICS & ENGINEERING", code: "MEC-015", title: "Snell's Law", formula: "n₁sinθ₁ = n₂sinθ₂", subtitle: "How light bends when crossing between materials.", deepElaboration: "When light passes from one medium to another, it refracts (bends) according to Snell's law. n is the refractive index (speed of light ratio: n = c/v). Higher n = slower light = more bending. Total internal reflection occurs when θ₁ > critical angle: sinθ_c = n₂/n₁. Applications: lenses, fiber optics (TIR keeps light trapped in glass), prisms, rainbows, mirages, and endoscopes.", exampleText: "A straw in a glass of water appears 'broken' at the surface — light bends when crossing from water (n=1.33) to air (n=1.0). Fiber optics trap light inside glass using total internal reflection — Snell's law at work across the internet.", examplePictogram: "light.beacon.max", icon: "light.beacon.max")
]
