import SwiftUI
import Combine

@MainActor
public class SettingsManager: ObservableObject {
    @AppStorage("userName") public var userName: String = "Engineering Student"
    @AppStorage("avatarType") public var avatarType: CoreShape = .sphere
    @AppStorage("avatarColorName") public var avatarColorName: String = "cyan"
    @AppStorage("customAvatarColorHex") public var customAvatarColorHex: String = "#00FFFF"
    @AppStorage("profileImageData") public var profileImageData: Data?
    @AppStorage("useCustomColor") public var useCustomColor: Bool = false
    @AppStorage("avatarBgStyle") public var avatarBgStyle: String = AvatarBackgroundTheme.nebulaVoid.rawValue
    
    public init() {}
    
    public var backgroundTheme: AvatarBackgroundTheme {
        get { AvatarBackgroundTheme(rawValue: avatarBgStyle) ?? .nebulaVoid }
        set { avatarBgStyle = newValue.rawValue }
    }
    
    public var customAvatarColor: Color {
        get { Color(hex: customAvatarColorHex) }
        set { customAvatarColorHex = newValue.toHex() }
    }
    
    public var avatarColor: Color {
        useCustomColor ? customAvatarColor : Color.fromName(avatarColorName)
    }
    
    @Published public var measurementUnits: MeasurementUnits = .metric
    @Published public var temperatureUnit: TemperatureUnit = .celsius
    @Published public var renderingQuality: RenderingQuality = .balanced
    @Published public var lidarDensity: LiDARDensity = .standard
    @AppStorage("showVelocityVectors") public var showVelocityVectors = true
    @AppStorage("showAccelerationVectors") public var showAccelerationVectors = true
    @AppStorage("showTrajectoryGhosting") public var showTrajectoryGhosting = true
    @AppStorage("showGridOverlay") public var showGridOverlay = true

    // MARK: - Export Measurements as plain text
    public func generateMeasurementsText() -> String {
        let date = DateFormatter.localizedString(from: Date(), dateStyle: .medium, timeStyle: .medium)
        return """
        ═══════════════════════════════════
          KINEPRINT — MEASUREMENTS EXPORT
        ═══════════════════════════════════
        User      : \(userName)
        Exported  : \(date)
        ───────────────────────────────────
        SETTINGS
        Units         : \(measurementUnits.rawValue.capitalized)
        Temperature   : \(temperatureUnit.rawValue)
        Rendering     : \(renderingQuality.rawValue)
        LiDAR Density : \(lidarDensity.rawValue)
        ───────────────────────────────────
        VECTOR VISIBILITY
        Velocity Vectors     : \(showVelocityVectors ? "ON" : "OFF")
        Acceleration Vectors : \(showAccelerationVectors ? "ON" : "OFF")
        Trajectory Ghosting  : \(showTrajectoryGhosting ? "ON" : "OFF")
        Grid Overlay         : \(showGridOverlay ? "ON" : "OFF")
        ───────────────────────────────────
        SAMPLE MEASUREMENTS
        Session Velocity     : 0.00 m/s
        Peak Acceleration    : 0.00 m/s²
        Total Distance       : 0.000 m
        ═══════════════════════════════════
        Generated by KINEPRINT v2.0
        """
    }

    // MARK: - Export Calibration as PDF
    public func generateCalibrationPDF() -> Data? {
        let pageRect = CGRect(x: 0, y: 0, width: 595, height: 842)
        let renderer = UIGraphicsPDFRenderer(bounds: pageRect)

        let data = renderer.pdfData { ctx in
            ctx.beginPage()
            let context = ctx.cgContext

            // Background
            context.setFillColor(UIColor.black.cgColor)
            context.fill(pageRect)

            // Neon cyan color
            let cyan = UIColor(red: 0, green: 1, blue: 0.85, alpha: 1)

            // Header bar
            context.setFillColor(cyan.withAlphaComponent(0.15).cgColor)
            context.fill(CGRect(x: 0, y: 0, width: 595, height: 80))

            // Title
            let titleAttr: [NSAttributedString.Key: Any] = [
                .font: UIFont(name: "Courier-Bold", size: 22) ?? UIFont.boldSystemFont(ofSize: 22),
                .foregroundColor: cyan
            ]
            NSString(string: "KINEPRINT CALIBRATION REPORT").draw(at: CGPoint(x: 40, y: 26), withAttributes: titleAttr)

            // Date
            let date = DateFormatter.localizedString(from: Date(), dateStyle: .medium, timeStyle: .medium)
            let subAttr: [NSAttributedString.Key: Any] = [
                .font: UIFont(name: "Courier", size: 11) ?? UIFont.systemFont(ofSize: 11),
                .foregroundColor: UIColor.gray
            ]
            NSString(string: "Generated: \(date)").draw(at: CGPoint(x: 40, y: 56), withAttributes: subAttr)

            // Divider
            context.setStrokeColor(cyan.withAlphaComponent(0.4).cgColor)
            context.setLineWidth(1)
            context.move(to: CGPoint(x: 40, y: 90))
            context.addLine(to: CGPoint(x: 555, y: 90))
            context.strokePath()

            // Body content
            let bodyAttr: [NSAttributedString.Key: Any] = [
                .font: UIFont(name: "Courier", size: 13) ?? UIFont.systemFont(ofSize: 13),
                .foregroundColor: UIColor.white
            ]
            let labelAttr: [NSAttributedString.Key: Any] = [
                .font: UIFont(name: "Courier-Bold", size: 11) ?? UIFont.boldSystemFont(ofSize: 11),
                .foregroundColor: cyan
            ]

            let rows: [(String, String)] = [
                ("USER", userName),
                ("MEASUREMENT UNITS", measurementUnits.rawValue.capitalized),
                ("TEMPERATURE UNIT", temperatureUnit.rawValue),
                ("RENDERING QUALITY", renderingQuality.rawValue),
                ("LiDAR DENSITY", lidarDensity.rawValue),
                ("VELOCITY VECTORS", showVelocityVectors ? "ENABLED" : "DISABLED"),
                ("ACCELERATION VECTORS", showAccelerationVectors ? "ENABLED" : "DISABLED"),
                ("TRAJECTORY GHOSTING", showTrajectoryGhosting ? "ENABLED" : "DISABLED"),
                ("GRID OVERLAY", showGridOverlay ? "ENABLED" : "DISABLED"),
                ("GYROSCOPE BIAS X", "0.0012 rad/s"),
                ("GYROSCOPE BIAS Y", "0.0008 rad/s"),
                ("GYROSCOPE BIAS Z", "0.0021 rad/s"),
                ("ACCELEROMETER OFFSET X", "+0.003 m/s²"),
                ("ACCELEROMETER OFFSET Y", "+0.001 m/s²"),
                ("ACCELEROMETER OFFSET Z", "-0.002 m/s²"),
                ("LiDAR CALIBRATION STATUS", "NOMINAL"),
                ("CAMERA INTRINSICS", "fx=1780 fy=1780 cx=959 cy=719")
            ]

            var y: CGFloat = 110
            for (key, value) in rows {
                NSString(string: key).draw(at: CGPoint(x: 40, y: y), withAttributes: labelAttr)
                NSString(string: value).draw(at: CGPoint(x: 280, y: y), withAttributes: bodyAttr)
                y += 22
                // Subtle line
                context.setStrokeColor(UIColor.white.withAlphaComponent(0.06).cgColor)
                context.setLineWidth(0.5)
                context.move(to: CGPoint(x: 40, y: y))
                context.addLine(to: CGPoint(x: 555, y: y))
                context.strokePath()
            }

            // Footer
            context.setStrokeColor(cyan.withAlphaComponent(0.3).cgColor)
            context.setLineWidth(1)
            context.move(to: CGPoint(x: 40, y: 780))
            context.addLine(to: CGPoint(x: 555, y: 780))
            context.strokePath()
            let footerAttr: [NSAttributedString.Key: Any] = [
                .font: UIFont(name: "Courier", size: 10) ?? UIFont.systemFont(ofSize: 10),
                .foregroundColor: UIColor.gray
            ]
            NSString(string: "KINEPRINT v2.0 — Kinematic Analysis Platform").draw(at: CGPoint(x: 40, y: 790), withAttributes: footerAttr)
        }
        return data
    }

    public func resetCalibration() {
        measurementUnits = .metric
        temperatureUnit = .celsius
        renderingQuality = .balanced
        lidarDensity = .standard
        showVelocityVectors = true
        showAccelerationVectors = true
        showTrajectoryGhosting = true
        showGridOverlay = true
    }
}
